### PR TITLE
Add twilio-pool-max to client

### PR DESCRIPTION
**Pull request by quady**
Related to: https://github.com/g5search/g5-hub/pull/222

### CODE REVIEW

**Comment by quady** [comment]
@perryqh @dpetersen As the top contributors here, any ideas why this change would be blowing up on the ruby 1.9.3 tests on travis-ci? It works locally even on 1.9.3.  Also, do we care about supporting 1.9.3 still?

**Comment by perryqh** [comment]
No and no.

I'm not sure why it would fail 1.9.3. It probably fails even without your change.

I'm unaware of an Orion app using a ruby < 2.1

**Comment by quady** [comment]
Looks like it is meant for core:
https://github.com/G5/g5_foundation_client/blob/master/.travis.yml#L4

But Core does not appear to use g5_foundation_client.

**Comment by dpetersen** [comment]
https://github.com/G5/g5_foundation_client/commit/d6d9b5b36d197bcd76ae6b76efdea7ea34dcacee

`Includes three Ruby versions that match the apps I think might use this.`

The version of bundler it's using is ancient. You can see in [this PR](https://github.com/bundler/bundler/issues/3558) that everybody and their brother is updating the bundler gem in their travis.yml before it runs specs. The version of bundler used for the specs in ruby 2.x is not as old.

So either delete the 1.9 bits altogether if this will never have to run in core, or add that line to your travis.yml.

**Pull request merged**
